const CLOSE_INSERT_DIALOG_AND_SAVE = 'CLOSE_DIALOG_AND_SAVE';
const CLOSE_INSERT_DIALOG_WITHOUT_SAVE = 'CLOSE_DIALOG_WITHOUT_SAVE';
const CLOSE_UPDATE_DIALOG_AND_UPDATE = 'CLOSE_DIALOG_AND_UPDATE';
const SET_ERROR = 'SET_ERROR';
const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
const OPEN_INSERT_DIALOG = 'OPEN_DIALOG';
const OPEN_UPDATE_DIALOG = 'OPEN_UPDATE_DIALOG';
const CLOSE_UPDATE_DIALOG_WITHOUT_SAVE = 'CLOSE_UPDATE_DIALOG_WITHOUT_SAVE';

export {
  CLOSE_INSERT_DIALOG_AND_SAVE,
  SET_ERROR,
  CLOSE_INSERT_DIALOG_WITHOUT_SAVE,
  CLOSE_UPDATE_DIALOG_AND_UPDATE,
  OPEN_INSERT_DIALOG,
  OPEN_UPDATE_DIALOG,
  UPDATE_PRODUCTS,
  CLOSE_UPDATE_DIALOG_WITHOUT_SAVE,
};
