
# production environment
FROM nginx:1.16.0-alpine
COPY ./build /usr/share/nginx/html
COPY nginx-beta.conf /etc/nginx/nginx.conf
COPY certs /etc/nginx/certs
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
