# build environment
FROM node:12.13.0-stretch as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ENV REACT_APP_ENV staging
COPY package.json /app/package.json
RUN npm install --production --ignore-scripts --silent
RUN npm install react-scripts -g --silent
COPY . /app
RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


# docker build --tag dashboard:prod .
# docker run -it -p 80:80 --rm dashboard:prod
