export const RoutesPaths = {
  Admin: {
    Login: '/admin/login',
    Home: '/admin/',
    Dashboard: '/admin/dashboard',
    User: '/admin/user',
    Questions: '/admin/questions',
    QuestionsDetails: '/admin/questions/edit',
    Typography: '/admin/typography',
    Icons: '/admin/icons',
    Notifications: '/admin/notifications',
    Services: '/admin/services',
    ServiceDetails: '/admin/services/edit',
    Logout: '/admin/logout',
    PostQuestion: '/admin/postQuestion',
    Evaluations: '/admin/viewEvaluations',
  },
  App: {
    Login: '/login',
    Signup: '/signup',
    Logout: '/logout',
    FreelancerProfile: '/user/profile',
    FreelancerSuccess: '/user/success',
    SubmitAnswerNote: '/answer/success',
    LandingPage: '/',
    ContactUs: '/contactUs',
    Solutions: '/solutions',
    Dashboard: '/dashboard',
    Questions: '/questions',
    AnswerQuestion: '/question/answer',
    ServiceDetails: '/services/details',
    CallEvaluation: '/services/evaluation',
    EditServiceRequest: '/service/edit',
    EditProfile: '/user/edit',
    Meetings: '/meeting/list',
    MeetingDetails: '/meeting/edit',
    AllNotifications: '/notifications',
    Services: '/services/list',
    ActivitiesList: '/activities/list',
    UserTypeSelection: '/user/type',
    NotFound: '/error',
  },
};
