export const RoutesPaths = {
  Admin: {
    Login: '/admin/login',
    Home: '/admin/',
    Dashboard: '/admin/dashboard',
    User: '/admin/user',
    Questions: '/admin/questions',
    QuestionsDetails: '/admin/questions/edit',
    Typography: '/admin/typography',
    Icons: '/admin/icons',
    Notifications: '/admin/notifications',
    Services: '/admin/services',
    ServiceDetails: '/admin/services/edit',
    Logout: '/admin/logout',
    PostQuestion: '/admin/postQuestion',
  },
  App: {
    Login: '/login',
    Signup: '/signup',
    Logout: '/logout',
    FreelancerProfile: '/user/profile',
    FreelancerSuccess: '/user/success',
    SubmitAnswerNote: '/answer/success',
    Home: '/',
    Questions: '/questions',
    QuestionsDetails: '/questions/view',
    AnswerQuestion: '/question/answer',
    ServiceRequestDetails: '/service/edit',
    EditProfile: '/user/edit',
    Meetings: '/meeting/list',
    MeetingDetails: '/meeting/edit',
    AllNotifications: '/notifications',
    Services: '/services/list',
  },
};
