const QuestionRoasterActionTypes = {
  UPDATE_QUESTIONS: 'UPDATE_QUESTIONS',
  ADD_FIELD_FILTER: 'ADD_FIELD_FILTER',
  REMOVE_FIELD_FILTER: 'REMOVE_FIELD_FILTER',
  RESET_FIELDS_FILTERS: 'RESET_FIELDS_FILTERS',
  ADD_LANGUAGE_FILTER: 'ADD_LANGUAGE_FILTER',
};

export default QuestionRoasterActionTypes;
