export const UPDATE_USERS = 'UPDATE_USERS';
export const SET_INSERT_DIALOG_OPEN = 'SET_INSERT_DIALOG_OPEN';
export const SET_UPDATE_DIALOG_OPEN = 'SET_UPDATE_DIALOG_OPEN';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const CLOSE_INSERT_DIALOG_AND_SAVE = 'CLOSE_INSERT_DIALOG_AND_SAVE';
export const CLOSE_UPDATE_DIALOG_AND_SAVE = 'CLOSE_UPDATE_DIALOG_AND_SAVE';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
