export const UPDATE_CLIENTS = 'UPDATE_CLIENTS';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const UPDATE_CURRENT_CLIENT = 'UPDATE_CURRENT_CLIENT';
export const VERIFY_CLIENT = 'VERIFY_CLIENT';
export const VERIFY_CURRENT_CLIENT = 'VERIFY_CURRENT_CLIENT';
